# Generated by Django 5.2.6 on 2025-09-28 11:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Broker',
            fields=[
                ('brokername', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('mobileno', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('openingdebit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('openingcredit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('remark', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='HeadParty',
            fields=[
                ('partyname', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('add1', models.CharField(blank=True, max_length=200)),
                ('add2', models.CharField(blank=True, max_length=200)),
                ('city', models.CharField(blank=True, max_length=100)),
                ('state', models.CharField(blank=True, max_length=100)),
                ('mobile', models.CharField(blank=True, max_length=15)),
                ('otherno', models.CharField(blank=True, max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('remark', models.TextField(blank=True)),
                ('openingdebit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
                ('openingcredit', models.DecimalField(blank=True, decimal_places=2, default=0, max_digits=10, null=True)),
            ],
        ),
    ]
