# Generated by Django 5.2.6 on 2025-09-28 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeadItem',
            fields=[
                ('item_name', models.CharField(max_length=100, primary_key=True, serialize=False)),
            ],
        ),
    ]
