# Generated by Django 5.2.6 on 2025-10-03 11:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0003_salemaster_saledetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurchaseMaster',
            fields=[
                ('invno', models.AutoField(primary_key=True, serialize=False)),
                ('invdate', models.DateField()),
                ('awakno', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicleno', models.CharField(blank=True, max_length=50, null=True)),
                ('totalamt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('borapercent', models.DecimalField(decimal_places=2, default=0, max_digits=5)),
                ('boraamt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dr', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('dramt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('other', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('advance', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('netamt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('amt_in_words', models.CharField(blank=True, max_length=255, null=True)),
                ('broker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokerapp.broker')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokerapp.headparty')),
            ],
        ),
        migrations.CreateModel(
            name='PurchaseDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bora', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('qty', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('rate', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('partywt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('millwt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('diffwt', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokerapp.headitem')),
                ('purchasemaster', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='brokerapp.purchasemaster')),
            ],
        ),
    ]
