# Generated by Django 5.2.6 on 2025-10-04 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0004_purchasemaster_purchasedetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='JamaEntry',
            fields=[
                ('entry_no', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='jama_entries', to='brokerapp.dailypage')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brokerapp.headparty')),
            ],
            options={
                'ordering': ['entry_no'],
            },
        ),
        migrations.CreateModel(
            name='NaameEntry',
            fields=[
                ('entry_no', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=14)),
                ('remark', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('daily_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='naame_entries', to='brokerapp.dailypage')),
                ('party', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='brokerapp.headparty')),
            ],
            options={
                'ordering': ['entry_no'],
            },
        ),
    ]
