# Generated by Django 5.2.6 on 2025-10-04 06:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0005_dailypage_jamaentry_naameentry'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jamaentry',
            name='party',
            field=models.ForeignKey(db_column='partyname', on_delete=django.db.models.deletion.PROTECT, to='brokerapp.headparty'),
        ),
        migrations.AlterField(
            model_name='naameentry',
            name='party',
            field=models.ForeignKey(db_column='partyname', on_delete=django.db.models.deletion.PROTECT, to='brokerapp.headparty'),
        ),
    ]
