# Generated by Django 5.2.6 on 2025-10-09 06:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0006_alter_jamaentry_party_alter_naameentry_party'),
    ]

    operations = [
        migrations.RenameField(
            model_name='salemaster',
            old_name='boraamt',
            new_name='batavamt',
        ),
        migrations.RenameField(
            model_name='salemaster',
            old_name='borapercent',
            new_name='batavpercent',
        ),
        migrations.RemoveField(
            model_name='salemaster',
            name='amt_in_words',
        ),
        migrations.AddField(
            model_name='saledetails',
            name='bn',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saledetails',
            name='bnwt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saledetails',
            name='bo',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saledetails',
            name='bowt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='saledetails',
            name='lotno',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='salemaster',
            name='extra',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='salemaster',
            name='qi',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AlterField(
            model_name='saledetails',
            name='salemaster',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='details', to='brokerapp.salemaster'),
        ),
    ]
