# Generated by Django 5.2.6 on 2025-10-09 07:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0007_rename_boraamt_salemaster_batavamt_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jamaentry',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='brokerapp.broker'),
        ),
        migrations.AddField(
            model_name='naameentry',
            name='broker',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='brokerapp.broker'),
        ),
    ]
