# Generated by Django 5.2.6 on 2025-11-01 05:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0010_organization_membership'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='broker',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brokerapp.organization'),
        ),
        migrations.AddField(
            model_name='dailypage',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brokerapp.organization'),
        ),
        migrations.AddField(
            model_name='headitem',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brokerapp.organization'),
        ),
        migrations.AddField(
            model_name='headparty',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brokerapp.organization'),
        ),
        migrations.AddField(
            model_name='purchasemaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='purchasemaster',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brokerapp.organization'),
        ),
        migrations.AddField(
            model_name='salemaster',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='salemaster',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brokerapp.organization'),
        ),
        migrations.AlterField(
            model_name='dailypage',
            name='date',
            field=models.DateField(),
        ),
        migrations.AddConstraint(
            model_name='dailypage',
            constraint=models.UniqueConstraint(fields=('org', 'date'), name='uniq_dailypage_per_org_date'),
        ),
    ]
