# Generated by Django 5.2.6 on 2025-11-01 13:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0012_alter_broker_org_alter_dailypage_org_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='broker',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brokerapp.organization'),
        ),
        migrations.AlterField(
            model_name='dailypage',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brokerapp.organization'),
        ),
        migrations.AlterField(
            model_name='headitem',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brokerapp.organization'),
        ),
        migrations.AlterField(
            model_name='headparty',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brokerapp.organization'),
        ),
        migrations.AlterField(
            model_name='purchasemaster',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brokerapp.organization'),
        ),
        migrations.AlterField(
            model_name='salemaster',
            name='org',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='brokerapp.organization'),
        ),
    ]
