# Generated by Django 5.2.6 on 2025-11-02 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0013_alter_broker_org_alter_dailypage_org_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetails',
            name='tbwt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='TBWt'),
        ),
    ]
