# Generated by Django 5.2.6 on 2025-11-12 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brokerapp', '0015_alter_organization_owner_delete_membership'),
    ]

    operations = [
        migrations.AddField(
            model_name='saledetails',
            name='frkwt',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='FrkWt'),
        ),
    ]
